---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couch-vol-0
  labels:
    volume: couch-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-8f547724
    volumeAttributes:
      path: /couchdb-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couch-vol-1
  labels:
    volume: couch-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-8f547724
    volumeAttributes:
      path: /couchdb-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couch-vol-2
  labels:
    volume: couch-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-8f547724
    volumeAttributes:
      path: /couchdb-2

